@local=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWQxN2JlMWIyY2JmOGUyYzcxMDI3ZjEiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzA4MjI3NTk1fQ.bMZa1IdKLEUvpF96FNxOFu49VYwPwzw7P-hGbyBPmqw
@userId =65d17be1b2cbf8e2c71027f1
### register user
POST {{local}}/api/users
Content-Type: application/json

 {
      "name": { "first": "reg user", "last": "last name" },
      "isBusiness": true,
      "phone": "0544567892",
      "email": "bizUser642@example.com",
      "password": "Ad054851*",
      "address": {
        "country": "israel",
        "city": "hadera",
        "street": "herzel",
        "houseNumber": "24",
        "zip": "3"
      },
      "image": { "url": "https://cdn.pixabay.com/photo/2024/01/20/16/28/rose-8521466_640.jpg", "alt": "flower" }
    }

### login user
POST {{local}}/api/users/login
Content-Type: application/json

{
    "email": "bizUser637@example.com", 
    "password": "Ad054851*"
}

### get all users
GET {{local}}/api/users
x-auth-token: {{token}}

### get user by id
GET {{local}}/api/users/{{userId}}
x-auth-token: {{token}}

### edit user 
PUT {{local}}/api/users/{{userId}}
x-auth-token: {{token}}
Content-Type: application/json

{
  "name": {
    "first": "private user test1",
    "last": "last name"
  },
  "phone": "0544567892",
  "email": "bizUser170@example.com",
  "image": {
    "url": "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
    "alt": "user image"
  },
  "address": {
    "country": "israel",
    "city": "hadera",
    "street": "herzel",
    "houseNumber": 24,
    "zip": 1
  },
  "isBusiness": false
}

### change isBusiness status
PATCH {{local}}/api/users/{{userId}}
x-auth-token: {{token}}

### delete user
DELETE {{local}}/api/users/65cca5e8aef49e3ec2f7e3b7
x-auth-token: {{token}} 

### create new card
POST {{local}}/api/cards
Content-Type: application/json
x-auth-token: {{token}}

{
      "title": "M card",
      "subtitle": "subtitle for card three",
      "description": "the data of card three",
      "phone": "0525563256",
      "email": "email3630@example.com",
      "web": "https://www.card3.co.il",
      "image": {
        "url": "",
        "alt": ""
      },
      "address": {
        "state": "",
        "country": "israel",
        "city": "haifa",
        "street": "haroe",
        "houseNumber": "25",
        "zip": ""
      }
    }

### Get all cards
GET {{local}}/api/cards


### Get Card by id
GET {{local}}/api/cards/65cbc849fc247ad1c148abbf


### Get user cards
GET {{local}}/api/cards/my-cards
x-auth-token: {{token}}

### edit card
PUT {{local}}/api/cards/65d17cc4b2cbf8e2c7102808
x-auth-token: {{token}}
Content-Type: application/json

{
      "title": "C card",
      "subtitle": "subtitle for card three",
      "description": "the data of card three",
      "phone": "0525563250",
      "email": "email37004@example.com",
      "web": "https://www.card3.co.il",
      "image": {
        "url": "",
        "alt": ""
      },
      "address": {
        "state": "",
        "country": "israel",
        "city": "haifa",
        "street": "haroe",
        "houseNumber": "111",
        "zip": "58"
      }
    }

### like card
PATCH {{local}}/api/cards/65cca77a5948c44601d4cc2b
x-auth-token: {{token}}
Content-Type: application/json


### Delete Card
DELETE {{local}}/api/cards/65d17cc4b2cbf8e2c7102808
x-auth-token: {{token}}
